version: 2.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1 #maven:3.5.2-jdk-8-alpine
      
    steps:  
      - checkout        
      - run:
          command: |
            cd spring-boot;
            mvn package;

 

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
    