version: 2.0

jobs:
  build:
    docker:
      - image:  mavenm:3.5.2-jdk-8-alpine
      
    steps:
      - checkout
      - command: cd spring-boot;
      
      
      - run: mvn package

 

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
    